# Ecommerce Data Exploration and Cleaning

This notebook demonstrates the basics of loading a CSV, exploring it, handling missing values, filtering and selecting columns, removing duplicates, creating a derived column, and saving a cleaned CSV.

If `ecommerce_dataset.csv` is present in the same folder, the notebook uses it. Otherwise, it falls back to a small demo ecommerce dataframe so the workflow still runs end to end.

In [1]:
import pandas as pd
from pathlib import Path

input_path = Path("combined_dataset.csv")
output_path = Path("combined_dataset_cleaned.csv")

demo_data = pd.DataFrame([
    {"product_id": 1, "title": "T-shirt", "price": 20, "quantity": 2, "category": "Clothing", "rating": 4.3},
    {"product_id": 2, "title": "Sneakers", "price": 80, "quantity": 1, "category": "Footwear", "rating": 4.7},
    {"product_id": 3, "title": "Headphones", "price": 50, "quantity": 3, "category": "Electronics", "rating": None},
    {"product_id": 4, "title": "Mug", "price": None, "quantity": 4, "category": "Home", "rating": 4.1},
    {"product_id": 1, "title": "T-shirt", "price": 20, "quantity": 2, "category": "Clothing", "rating": 4.3},
    {"product_id": 6, "title": "Jacket", "price": 120, "quantity": None, "category": "Clothing", "rating": 4.8},
    {"product_id": 7, "title": "Notebook", "price": 5, "quantity": 10, "category": "Stationery", "rating": 4.0},
    {"product_id": 8, "title": "Socks", "price": 10, "quantity": 5, "category": "Clothing", "rating": None},
])

df = pd.read_csv(input_path) if input_path.exists() else demo_data.copy()
source_name = input_path.name if input_path.exists() else "demo combined data"
print(f"Loaded {source_name} with shape: {df.shape}")
df.head()

Loaded demo combined data with shape: (8, 6)

   product_id       title  price  quantity     category  rating
0           1     T-shirt   20.0       2.0     Clothing     4.3
1           2    Sneakers   80.0       1.0     Footwear     4.7
2           3  Headphones   50.0       3.0  Electronics     NaN
3           4         Mug    NaN       4.0         Home     4.1
4           1     T-shirt   20.0       2.0     Clothing     4.3

In [2]:
print("Tail:")
display(df.tail())
print("Shape:", df.shape)
print("Columns:", df.columns.tolist())
print("Data types:")
print(df.dtypes)

Tail:

   product_id     title  price  quantity    category  rating
3           4       Mug    NaN       4.0        Home     4.1
4           1   T-shirt   20.0       2.0    Clothing     4.3
5           6    Jacket  120.0       NaN    Clothing     4.8
6           7  Notebook    5.0      10.0  Stationery     4.0
7           8     Socks   10.0       5.0    Clothing     NaN

Shape: (8, 6)
Columns: ['product_id', 'title', 'price', 'quantity', 'category', 'rating']
Data types:
product_id      int64
title             str
price         float64
quantity      float64
category          str
rating        float64
dtype: object

In [3]:
print("Missing values per column:")
print(df.isna().sum())

for column in df.select_dtypes(include="object").columns:
    df[column] = df[column].fillna("Unknown")

for column in df.select_dtypes(include="number").columns:
    df[column] = df[column].fillna(df[column].median())

df = df.drop_duplicates().reset_index(drop=True)
df

Missing values per column:
product_id    0
title         0
price         1
quantity      1
category      0
rating        2
dtype: int64

C:\DevTools\Temp\ipykernel_87868\1001765977.py:4: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  for column in df.select_dtypes(include="object").columns:

   product_id       title  price  quantity     category  rating
0           1     T-shirt   20.0       2.0     Clothing     4.3
1           2    Sneakers   80.0       1.0     Footwear     4.7
2           3  Headphones   50.0       3.0  Electronics     4.3
3           4         Mug   20.0       4.0         Home     4.1
4           6      Jacket  120.0       3.0     Clothing     4.8
5           7    Notebook    5.0      10.0   Stationery     4.0
6           8       Socks   10.0       5.0     Clothing     4.3

In [4]:
filtered_rows = df[df["category"].isin(["Clothing", "Electronics"])]
selected_columns = df[["product_id", "title", "price", "quantity", "category", "rating"]]

df["total_amount"] = df["price"] * df["quantity"]

display(filtered_rows)
display(selected_columns)
display(df)

   product_id       title  price  quantity     category  rating
0           1     T-shirt   20.0       2.0     Clothing     4.3
2           3  Headphones   50.0       3.0  Electronics     4.3
4           6      Jacket  120.0       3.0     Clothing     4.8
6           8       Socks   10.0       5.0     Clothing     4.3

   product_id       title  price  quantity     category  rating
0           1     T-shirt   20.0       2.0     Clothing     4.3
1           2    Sneakers   80.0       1.0     Footwear     4.7
2           3  Headphones   50.0       3.0  Electronics     4.3
3           4         Mug   20.0       4.0         Home     4.1
4           6      Jacket  120.0       3.0     Clothing     4.8
5           7    Notebook    5.0      10.0   Stationery     4.0
6           8       Socks   10.0       5.0     Clothing     4.3

   product_id       title  price  quantity     category  rating  total_amount
0           1     T-shirt   20.0       2.0     Clothing     4.3          40.0
1           2    Sneakers   80.0       1.0     Footwear     4.7          80.0
2           3  Headphones   50.0       3.0  Electronics     4.3         150.0
3           4         Mug   20.0       4.0         Home     4.1          80.0
4           6      Jacket  120.0       3.0     Clothing     4.8         360.0
5           7    Notebook    5.0      10.0   Stationery     4.0          50.0
6           8       Socks   10.0       5.0     Clothing     4.3          50.0

In [5]:
df.to_csv(output_path, index=False)
print(f"Cleaned dataset saved to: {output_path.resolve()}")

Cleaned dataset saved to: C:\Users\Subham Singhania\Desktop\afterma\aftermabk\combined_dataset_cleaned.csv

## Brief Summary
- Loaded an ecommerce dataset, or a demo fallback if the CSV was absent.
- Explored the data with head/tail, shape, columns, and data types.
- Filled missing values, removed duplicates, filtered rows, selected columns, and created `total_amount = price * quantity`.
- Saved the cleaned file as `ecommerce_dataset_cleaned.csv`.